name: sc-blipper-gpu
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.10
  - pip
  - zlib
  - libcurl
  - openssl
  - curl
  - r-seurat>=5
  - r-anndata
  - r-reticulate
  - r-optparse
  - r-remotes
  - r-ggplotify
  - r-pheatmap
  - r-ggraph
  - r-igraph
  - r-rcurl
  - r-r.utils
  - bioconductor-biomart
  - bioconductor-fgsea>=1.32
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.6.0+cu126
    - h5py
    - "cnmf[gpu] @ git+https://github.com/TrynkaLab/cNMF.git"
    - pandas
    - scanpy
    - scikit-misc
    - decoupler>=2.1
