name: sc-blipper-scvi
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - torch
    - torchvision
    - jax[cuda12]
    - scvi-tools 
    - scikit-misc
    - ipython
    - tqdm